version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce
  
  PgAdmin:
   image: dpage/pgadmin4

  DiscountDb:
   image: postgres

  basketdb:
    image: redis:alpine

  catalogdb:
    image: mongo:latest

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  mongo_data:
  portainer_data: 
  postgres_data:
  pgadmin_data:  

